<?php

$countrycallingcodes = array (
        'AF' => 93, //Afghanistan
        'AX' => 358, //Aland Islands (Finland)
        'AL' => 355, //Albania
        'DZ' => 213, //Algeria
        'AS' => 684, //American Samoa
        'AD' => 376, //Andorra
        'AO' => 244, //Angola
        'AI' => 1, //Anguilla (1 264)
        'AQ' => 672, //Antarctica
        'AG' => 1, //Antigua And Barbuda
        'AR' => 54, //Argentina
        'AM' => 374, //Armenia
        'AW' => 297, //Aruba
        'AU' => 61, //Australia
        'AT' => 43, //Austria
        'AZ' => 994, //Azerbaijan
        'BS' => 1, //Bahamas
        'BH' => 973, //Bahrain
        'BD' => 880, //Bangladesh
        'BB' => 1, //Barbados
        'BY' => 375, //Belarus
        'BE' => 32, //Belgium
        'BZ' => 501, //Belize
        'BJ' => 229, //Benin
        'BM' => 1, //Bermuda
        'BT' => 975, //Bhutan
        'BO' => 591, //Bolivia
        'BA' => 387, //Bosnia And Herzegovina
        'BW' => 267, //Botswana
        'BV' => 47, //Bouvet Island (Norway)
        'BR' => 55, //Brazil
        'IO' => 246, //British Indian Ocean Territory
        'BN' => 673, //Brunei Darussalam
        'BG' => 359, //Bulgaria
        'BF' => 226, //Burkina Faso
        'BI' => 257, //Burundi
        'KH' => 855, //Cambodia
        'CM' => 237, //Cameroon
        'CA' => 1, //Canada
        'CV' => 238, //Cape Verde
        'KY' => 1, //Cayman Islands
        'CF' => 236, //Central African Republic
        'TD' => 235, //Chad
        'CL' => 56, //Chile
        'CN' => 86, //China
        'CX' => 618, //Christmas Island
        'CC' => 61, //Cocos (Keeling) Islands
        'CO' => 57, //Colombia
        'KM' => 269, //Comoros
        'CG' => 242, //Congo
        'CD' => 243, //Congo, Democratic Republic
        'CK' => 682, //Cook Islands
        'CR' => 506, //Costa Rica
        'CI' => 225, //Ivory Coast
        'HR' => 385, //Croatia
        'CU' => 53, //Cuba
        'CY' => 357, //Cyprus
        'CZ' => 420, //Czech Republic
        'DK' => 45, //Denmark
        'DJ' => 253, //Djibouti
        'DM' => 1, //Dominica
        'DO' => 1, //Dominican Republic
        'EC' => 593, //Ecuador
        'EG' => 20, //Egypt
        'SV' => 503, //El Salvador
        'GQ' => 240, //Equatorial Guinea
        'ER' => 291, //Eritrea
        'EE' => 372, //Estonia
        'ET' => 251, //Ethiopia
        'FK' => 500, //Falkland Islands (Malvinas)
        'FO' => 298, //Faroe Islands
        'FJ' => 679, //Fiji
        'FI' => 358, //Finland
        'FR' => 33, //France
        'GF' => 594, //French Guiana
        'PF' => 689, //French Polynesia
        'TF' => false, //French Southern Territories
        'GA' => 241, //Gabon
        'GM' => 220, //Gambia
        'GE' => 995, //Georgia
        'DE' => 49, //Germany
        'GH' => 233, //Ghana
        'GI' => 350, //Gibraltar
        'GR' => 30, //Greece
        'GL' => 299, //Greenland
        'GD' => 1, //Grenada
        'GP' => 590, //Guadeloupe
        'GU' => 1, //Guam
        'GT' => 502, //Guatemala
        'GG' => 44, //Guernsey
        'GN' => 224, //Guinea
        'GW' => 245, //Guinea-Bissau
        'GY' => 592, //Guyana
        'HT' => 509, //Haiti
        'HM' => false, //Heard Island & Mcdonald Islands
        'VA' => 39, //Holy See (Vatican City State)
        'HN' => 504, //Honduras
        'HK' => 852, //Hong Kong
        'HU' => 36, //Hungary
        'IS' => 354, //Iceland
        'IN' => 91, //India
        'ID' => 62, //Indonesia
        'IR' => 98, //Iran, Islamic Republic Of
        'IQ' => 964, //Iraq
        'IE' => 353, //Ireland
        'IM' => 44, //Isle Of Man
        'IL' => 972, //Israel
        'IT' => 39, //Italy
        'JM' => 1, //Jamaica
        'JP' => 81, //Japan
        'JE' => 44, //Jersey
        'JO' => 962, //Jordan
        'KZ' => 7, //Kazakhstan
        'KE' => 254, //Kenya
        'KI' => 686, //Kiribati
        'KR' => 82, //Korea, Democratic Republic Of
        'KW' => 965, //Kuwait
        'KG' => false, // 996, //Kyrgyzstan
        'LA' => 856, //Lao People's Democratic Republic
        'LV' => 371, //Latvia
        'LB' => 961, //Lebanon
        'LS' => 266, //Lesotho
        'LR' => 231, //Liberia
        'LY' => 218, //Libyan Arab Jamahiriya
        'LI' => 423, //Liechtenstein
        'LT' => 370, //Lithuania
        'LU' => 352, //Luxembourg
        'MO' => 853, //Macao
        'MK' => 389, //Macedonia, Former Yugoslav Rep.
        'MG' => 261, //Madagascar
        'MW' => 265, //Malawi
        'MY' => 60, //Malaysia
        'MV' => 960, //Maldives
        'ML' => 223, //Mali
        'MT' => 356, //Malta
        'MH' => 692, //Marshall Islands
        'MQ' => 596, //Martinique
        'MR' => 222, //Mauritania
        'MU' => 230, //Mauritius
        'YT' => 269, //Mayotte
        'MX' => 52, //Mexico
        'FM' => false, //691, //Micronesia, Federated States Of
        'MD' => 373, //Moldova, Republic Of
        'MC' => 377, //Monaco
        'MN' => 976, //Mongolia
        'ME' => false, //382, //Montenegro
        'MS' => false, //1664, //Montserrat
        'MA' => 212, //Morocco
        'MZ' => 258, //Mozambique
        'MM' => 95, //Myanmar
        'NA' => 264, //Namibia
        'NR' => 674, //Nauru
        'NP' => 977, //Nepal
        'NL' => 31, //Netherlands
        'AN' => 599, //Netherlands Antilles
        'NC' => 687, //New Caledonia
        'NZ' => 64, //New Zealand
        'NI' => 505, //Nicaragua
        'NE' => 227, //Niger
        'NG' => 234, //Nigeria
        'NU' => 683, //Niue
        'NF' => false, //6723, //Norfolk Island
        'MP' => false, //1670, //Northern Mariana Islands
        'NO' => 47, //Norway
        'OM' => 968, //Oman
        'PK' => 92, //Pakistan
        'PW' => 680, //Palau
        'PS' => false, //970, //Palestinian Territory, Occupied
        'PA' => 507, //Panama
        'PG' => 675, //Papua New Guinea
        'PY' => 595, //Paraguay
        'PE' => 51, //Peru
        'PH' => 63, //Philippines
        'PN' => 64, //Pitcairn
        'PL' => 48, //Poland
        'PT' => 351, //Portugal
        'PR' => 1, //Puerto Rico
        'QA' => 974, //Qatar
        'RE' => 262, //Reunion
        'RO' => 40, //Romania
        'RU' => 7, //Russian Federation
        'RW' => 250, //Rwanda
        'BL' => false, //Saint Barthelemy
        'SH' => 290, //Saint Helena
        'KN' => false, //1869, //Saint Kitts And Nevis
        'LC' => 1, //Saint Lucia
        'MF' => false, //Saint Martin
        'PM' => 508, //Saint Pierre And Miquelon
        'VC' => 1, //Saint Vincent And Grenadines
        'WS' => 685, //Samoa
        'SM' => 378, //San Marino
        'ST' => 239, //Sao Tome And Principe
        'SA' => 966, //Saudi Arabia
        'SN' => 221, //Senegal
        'RS' => 381, //Serbia
        'SC' => 248, //Seychelles
        'SL' => 232, //Sierra Leone
        'SG' => 65, //Singapore
        'SK' => 421, //Slovakia
        'SI' => 386, //Slovenia
        'SB' => 677, //Solomon Islands
        'SO' => 252, //Somalia
        'ZA' => 27, //South Africa
        'GS' => false, //South Georgia And Sandwich Isl.
        'ES' => 34, //Spain
        'LK' => 94, //Sri Lanka
        'SD' => 249, //Sudan
        'SR' => 597, //Suriname
        'SJ' => 47, //Svalbard And Jan Mayen
        'SZ' => 268, //Swaziland
        'SE' => 46, //Sweden
        'CH' => 41, //Switzerland
        'SY' => 963, //Syrian Arab Republic
        'TW' => 886, //Taiwan, Province Of China
        'TJ' => 992, //Tajikistan
        'TZ' => 255, //Tanzania, United Republic Of
        'TH' => 66, //Thailand
        'TL' => 670, //Timor-Leste
        'TG' => 228, //Togo
        'TK' => 690, //Tokelau
        'TO' => 676, //Tonga
        'TT' => false, //Trinidad And Tobago
        'TN' => 216, //Tunisia
        'TR' => 90, //Turkey
        'TM' => 993, //Turkmenistan
        'TC' => false, //1649, //Turks And Caicos Islands
        'TV' => 688, //Tuvalu
        'UG' => 256, //Uganda
        'UA' => 380, //Ukraine
        'AE' => 971, //United Arab Emirates
        'GB' => 44, //United Kingdom
        'US' => 1, //United States
        'UM' => false, //United States Outlying Islands
        'UY' => 598, //Uruguay
        'UZ' => 998, //Uzbekistan
        'VU' => 678, //Vanuatu
        'VE' => 58, //Venezuela
        'VN' => 84, //Viet Nam
        'VG' => false, //Virgin Islands, British
        'VI' => false, //Virgin Islands, U.S.
        'WF' => 681, //Wallis And Futuna
        'EH' => 212, //Western Sahara
        'YE' => 967, //Yemen
        'ZM' => 260, //Zambia
        'ZW' => 263, //Zimbabwe
);

?>